language: node_js 
node_js:
  - 12
cache:
  directories:
  - node_modules # Cache the node_modules folder for quicker build times
script:
  - npm run build 
  - npm run export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true # Prevents Travis from resetting the working directory made during the build
  github_token: $github_token 
  local_dir: out
  on:
    branch: master
